### ISSUE TITLE
Add license? 

### ISSUE THREAD

**Issue by Neargye** [vitaut/_._#4]

**Comment by vitaut** [comment]
Good idea. Any suggestions which license to use?

**Comment by Neargye** [comment]
I think MIT ok for little project. 
Or Unlicense. 
I can help maintain this repo if you want. 
Think it's very funny, and wanna use this in some fun example.

**Comment by vitaut** [comment]
> I can help maintain this repo if you want.

Sent you an invite.

**Comment by Neargye** [comment]
@vitaut thanks. I will update project soon.

**Comment by Neargye** [comment]
Fix in 9e2c5606125013b54b3b5732a63b1e99e70f5b0e
