### ISSUE TITLE
Streaming operator is wrong

### ISSUE THREAD

**Issue by zivsha** [vitaut/_._#6]
You stream to `std::cout` always instead of streaming to the `std::ostream&` parameter...

**Comment by Neargye** [comment]
For now yes. I this how simple add parameters

**Comment by vitaut** [comment]
@zivsha could you elaborate what ostream parameter you are referring to?

**Comment by Neargye** [comment]
Maybe some think like `(_._).set_ostream(std::cin);`

**Comment by zivsha** [comment]
Actually, I think I missed the point of this class. But still, it would be nice to configure the steam of `asstream` to other streams besides `cout`.

**Comment by Neargye** [comment]
add function set_ostream/set_istream to asstream.
By default asstream = cout/cin, wide_asstream =  wcout/wcin.
